# Generated by Django 3.1.4 on 2021-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210119_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=280, verbose_name=''),
        ),
    ]
